name: bluetooth_hacker
description: Bluetooth Low-Energy service finder with psuedo-scripting capabilities.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # WIDGETS
  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.3.1 # widgets that make it easy to implement the BLoC design pattern
  flutter_platform_widgets: ^1.20.0 # Platform aware widgets

  # SERVICES
  flutter_reactive_ble: ^5.0.2 # BLE operations for multiple devices

  # DEPENDENCY INJECTION
  get_it: ^7.2.0 # simple Service Locator for Dart and Flutter projects

  # UTILITIES
  intl: ^0.17.0 # contains code to deal with internationalized/localized messages, date and number formatting and parsing, and other internationalization issues
  collection: ^1.15.0 # collections and utilities functions and classes related to collections
  logger: ^1.1.0 # small, easy to use and extensible logger which prints beautiful logs
  freezed: ^2.0.2 # Code generator for data-classes/unions/pattern-matching/cloning

  # TESTING
  # mocktail: ^0.3.0 # mock library inspired by mockito

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

  build_runner: ^2.1.4 # build system for Dart code generation and modular compilation

flutter:
  uses-material-design: true
